name: book_reader
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  easy_localization: ^3.0.2
  flutter_screenutil: ^5.8.4
  file_picker: ^5.3.3
  syncfusion_flutter_pdfviewer: ^22.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_slidable: ^3.0.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  provider: ^6.0.5
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  zoom_tap_animation: ^1.1.0
  path_provider: ^2.1.1

 





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/png/
    - assets/svg/
    - assets/translations/



  fonts:
     - family: Kanit
       fonts:
         - asset: assets/fonts/Kanit-Bold.ttf
         - asset: assets/fonts/Kanit-ExtraBold.ttf
         - asset: assets/fonts/Kanit-Italic.ttf
         - asset: assets/fonts/Kanit-Light.ttf
         - asset: assets/fonts/Kanit-Medium.ttf
         - asset: assets/fonts/Kanit-Regular.ttf
         - asset: assets/fonts/Kanit-SemiBold.ttf
         - asset: assets/fonts/Kanit-Thin.ttf

